/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_derklaro_reflexion_natives_FNativeReflect */

#ifndef _Included_dev_derklaro_reflexion_natives_FNativeReflect
#define _Included_dev_derklaro_reflexion_natives_FNativeReflect
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_derklaro_reflexion_natives_FNativeReflect
 * Method:    GetObjectFieldValue
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_dev_derklaro_reflexion_natives_FNativeReflect_GetObjectFieldValue
  (JNIEnv *, jclass, jstring, jstring, jstring, jobject);

/*
 * Class:     dev_derklaro_reflexion_natives_FNativeReflect
 * Method:    GetZFieldValue
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/Object;)Z
 */
JNIEXPORT jboolean JNICALL Java_dev_derklaro_reflexion_natives_FNativeReflect_GetZFieldValue
  (JNIEnv *, jclass, jstring, jstring, jobject);

/*
 * Class:     dev_derklaro_reflexion_natives_FNativeReflect
 * Method:    GetBFieldValue
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/Object;)B
 */
JNIEXPORT jbyte JNICALL Java_dev_derklaro_reflexion_natives_FNativeReflect_GetBFieldValue
  (JNIEnv *, jclass, jstring, jstring, jobject);

/*
 * Class:     dev_derklaro_reflexion_natives_FNativeReflect
 * Method:    GetCFieldValue
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/Object;)C
 */
JNIEXPORT jchar JNICALL Java_dev_derklaro_reflexion_natives_FNativeReflect_GetCFieldValue
  (JNIEnv *, jclass, jstring, jstring, jobject);

/*
 * Class:     dev_derklaro_reflexion_natives_FNativeReflect
 * Method:    GetSFieldValue
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/Object;)S
 */
JNIEXPORT jshort JNICALL Java_dev_derklaro_reflexion_natives_FNativeReflect_GetSFieldValue
  (JNIEnv *, jclass, jstring, jstring, jobject);

/*
 * Class:     dev_derklaro_reflexion_natives_FNativeReflect
 * Method:    GetIFieldValue
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_dev_derklaro_reflexion_natives_FNativeReflect_GetIFieldValue
  (JNIEnv *, jclass, jstring, jstring, jobject);

/*
 * Class:     dev_derklaro_reflexion_natives_FNativeReflect
 * Method:    GetLFieldValue
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/Object;)J
 */
JNIEXPORT jlong JNICALL Java_dev_derklaro_reflexion_natives_FNativeReflect_GetJFieldValue
  (JNIEnv *, jclass, jstring, jstring, jobject);

/*
 * Class:     dev_derklaro_reflexion_natives_FNativeReflect
 * Method:    GetFFieldValue
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/Object;)F
 */
JNIEXPORT jfloat JNICALL Java_dev_derklaro_reflexion_natives_FNativeReflect_GetFFieldValue
  (JNIEnv *, jclass, jstring, jstring, jobject);

/*
 * Class:     dev_derklaro_reflexion_natives_FNativeReflect
 * Method:    GetDFieldValue
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/Object;)D
 */
JNIEXPORT jdouble JNICALL Java_dev_derklaro_reflexion_natives_FNativeReflect_GetDFieldValue
  (JNIEnv *, jclass, jstring, jstring, jobject);

/*
 * Class:     dev_derklaro_reflexion_natives_FNativeReflect
 * Method:    SetObjectFieldValue
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/Object;Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_dev_derklaro_reflexion_natives_FNativeReflect_SetObjectFieldValue
  (JNIEnv *, jclass, jstring, jstring, jstring, jobject, jobject);

/*
 * Class:     dev_derklaro_reflexion_natives_FNativeReflect
 * Method:    SetZFieldValue
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/Object;Z)V
 */
JNIEXPORT void JNICALL Java_dev_derklaro_reflexion_natives_FNativeReflect_SetZFieldValue
  (JNIEnv *, jclass, jstring, jstring, jobject, jboolean);

/*
 * Class:     dev_derklaro_reflexion_natives_FNativeReflect
 * Method:    SetBFieldValue
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/Object;B)V
 */
JNIEXPORT void JNICALL Java_dev_derklaro_reflexion_natives_FNativeReflect_SetBFieldValue
  (JNIEnv *, jclass, jstring, jstring, jobject, jbyte);

/*
 * Class:     dev_derklaro_reflexion_natives_FNativeReflect
 * Method:    SetCFieldValue
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/Object;C)V
 */
JNIEXPORT void JNICALL Java_dev_derklaro_reflexion_natives_FNativeReflect_SetCFieldValue
  (JNIEnv *, jclass, jstring, jstring, jobject, jchar);

/*
 * Class:     dev_derklaro_reflexion_natives_FNativeReflect
 * Method:    SetSFieldValue
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/Object;S)V
 */
JNIEXPORT void JNICALL Java_dev_derklaro_reflexion_natives_FNativeReflect_SetSFieldValue
  (JNIEnv *, jclass, jstring, jstring, jobject, jshort);

/*
 * Class:     dev_derklaro_reflexion_natives_FNativeReflect
 * Method:    SetIFieldValue
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/Object;I)V
 */
JNIEXPORT void JNICALL Java_dev_derklaro_reflexion_natives_FNativeReflect_SetIFieldValue
  (JNIEnv *, jclass, jstring, jstring, jobject, jint);

/*
 * Class:     dev_derklaro_reflexion_natives_FNativeReflect
 * Method:    SetLFieldValue
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/Object;J)V
 */
JNIEXPORT void JNICALL Java_dev_derklaro_reflexion_natives_FNativeReflect_SetJFieldValue
  (JNIEnv *, jclass, jstring, jstring, jobject, jlong);

/*
 * Class:     dev_derklaro_reflexion_natives_FNativeReflect
 * Method:    SetFFieldValue
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/Object;F)V
 */
JNIEXPORT void JNICALL Java_dev_derklaro_reflexion_natives_FNativeReflect_SetFFieldValue
  (JNIEnv *, jclass, jstring, jstring, jobject, jfloat);

/*
 * Class:     dev_derklaro_reflexion_natives_FNativeReflect
 * Method:    SetDFieldValue
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/Object;D)V
 */
JNIEXPORT void JNICALL Java_dev_derklaro_reflexion_natives_FNativeReflect_SetDFieldValue
  (JNIEnv *, jclass, jstring, jstring, jobject, jdouble);

#ifdef __cplusplus
}
#endif
#endif
