/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_derklaro_reflexion_NativeReflection */

#ifndef _Included_com_github_derklaro_reflexion_NativeReflection
#define _Included_com_github_derklaro_reflexion_NativeReflection
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_derklaro_reflexion_NativeReflection
 * Method:    getFieldValue
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_github_derklaro_reflexion_NativeReflection_getFieldValue
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     com_github_derklaro_reflexion_NativeReflection
 * Method:    setFieldValue
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_github_derklaro_reflexion_NativeReflection_setFieldValue
  (JNIEnv *, jclass, jstring, jstring, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
