name: CI
on:
  pull_request:
  push:
    branches: [ '**' ]
    tags-ignore: [ '**' ]

jobs:
  build-native:
    name: Binary ${{ matrix.toolchain }} / ${{ matrix.platform.target }}
    runs-on: ${{ matrix.platform.os }}
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - stable
          - nightly
        platform:
          # x86_64
          - { os: 'macos-latest', target: 'x86_64-apple-darwin', cross: false }
          - { os: 'windows-latest', target: 'x86_64-pc-windows-msvc', cross: false }
          - { os: 'ubuntu-latest', target: 'x86_64-unknown-linux-gnu', cross: false }
          # ARM64
          - { os: 'ubuntu-latest', target: 'aarch64-unknown-linux-gnu', cross: true }
          - { os: 'ubuntu-latest', target: 'aarch64-unknown-linux-musl', cross: true }
          # ARMv7
          - { os: 'ubuntu-latest', target: 'armv7-unknown-linux-gnueabihf', cross: true }
          - { os: 'ubuntu-latest', target: 'armv7-unknown-linux-musleabihf', cross: true }
          # ARMv6
          - { os: 'ubuntu-latest', target: 'arm-unknown-linux-gnueabihf', cross: true }
          - { os: 'ubuntu-latest', target: 'arm-unknown-linux-musleabihf', cross: true }
          # Android
          - { os: 'ubuntu-latest', target: 'aarch64-linux-android', cross: true }
          - { os: 'ubuntu-latest', target: 'armv7-linux-androideabi', cross: true }
          - { os: 'ubuntu-latest', target: 'x86_64-linux-android', cross: true }
          - { os: 'ubuntu-latest', target: 'i686-linux-android', cross: true }
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install gcc-multilib
        if: matrix.platform.os == 'ubuntu-latest'
        run: sudo apt install -y gcc-multilib

      - name: Setup rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          override: true
          profile: minimal
          toolchain: ${{ matrix.toolchain }}
          target: ${{ matrix.platform.target }}

      - name: Build binary
        uses: actions-rs/cargo@v1
        with:
          command: build
          use-cross: ${{ matrix.platform.cross }}
          args: --release --target ${{ matrix.platform.target }} --manifest-path=native/Cargo.toml --no-default-features
